# .travis.yml
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
sudo: required

env:
  global:
    - WARNINGS_ARE_ERRORS=1
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - BOOTSTRAP_LATEX=""
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

#Missing deps/suggests:
#    knitr,
#    gbm,
#    caTools,
#    pbapply,
#    digest,
#    gridExtra,
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo mkdir -p /usr/lib/R/library
  - echo 'R_LIBS=/usr/lib/R/library:/usr/lib/R/site-library/' > ~/.Renviron
  - sudo chmod 2777 /usr/lib/R/library
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install car
  - ./travis-tool.sh r_binary_install reshape2
  - ./travis-tool.sh r_binary_install foreach
  - ./travis-tool.sh r_binary_install plyr
  - ./travis-tool.sh r_binary_install nlme
  - ./travis-tool.sh r_binary_install BradleyTerry2
  - ./travis-tool.sh r_binary_install e1071
  - ./travis-tool.sh r_binary_install earth
  - ./travis-tool.sh r_binary_install fastICA
  - ./travis-tool.sh r_binary_install gam
  - ./travis-tool.sh r_binary_install ipred
  - ./travis-tool.sh r_binary_install kernlab
  - ./travis-tool.sh r_binary_install klaR
  - ./travis-tool.sh r_binary_install MASS
  - ./travis-tool.sh r_binary_install ellipse
  - ./travis-tool.sh r_binary_install mda
  - ./travis-tool.sh r_binary_install mgcv
  - ./travis-tool.sh r_binary_install mlbench
  - ./travis-tool.sh r_binary_install nnet
  - ./travis-tool.sh r_binary_install party
  - ./travis-tool.sh r_binary_install pls
  - ./travis-tool.sh r_binary_install pROC
  - ./travis-tool.sh r_binary_install proxy
  - ./travis-tool.sh r_binary_install randomForest
  - ./travis-tool.sh r_binary_install RANN
  - ./travis-tool.sh r_binary_install spls
  - ./travis-tool.sh r_binary_install subselect
  - ./travis-tool.sh r_binary_install pamr
  - ./travis-tool.sh r_binary_install superpc
  - ./travis-tool.sh r_binary_install Cubist
  - ./travis-tool.sh r_binary_install testthat
  - ./travis-tool.sh r_binary_install rARPACK
  - ./travis-tool.sh r_binary_install ggplot2
  - ./travis-tool.sh r_binary_install reshape2
  - ./travis-tool.sh r_binary_install data.table
  - ./travis-tool.sh r_binary_install glmnet
  - ./travis-tool.sh r_binary_install rpart
  - ./travis-tool.sh r_binary_install kernlab
  - ./travis-tool.sh r_binary_install grid
  - ./travis-tool.sh r_binary_install lattice
  - ./travis-tool.sh github_package igraph/rigraph
  - ./travis-tool.sh github_package jimhester/covr@4cae287abde5e2cf0c3c73aedeaec4d902dfd3ed
  - ./travis-tool.sh github_package jimhester/lintr@21607f469c2ce4f999d04a836f9348038a7282e2
  - ./travis-tool.sh github_package hadley/devtools@52bc15bb7eb87105bbf799d7f784054921146c02
  - ./travis-tool.sh github_package hadley/testthat@c67018fa4970ee3390ea2056efe56726626b07e3'

install:
  - ./travis-tool.sh install_deps

script:
  - ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
